package com.chick.web.dictionary.entity;

import com.chick.common.domin.BaseEntity;

import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_db_info
 */
public class SysDbInfo extends BaseEntity {
    /**
     * Database Column Remarks:
     *   字典id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   父节点编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.parent_num
     *
     * @mbg.generated
     */
    private String parentNum;

    /**
     * Database Column Remarks:
     *   字典编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.data_num
     *
     * @mbg.generated
     */
    private String dataNum;

    /**
     * Database Column Remarks:
     *   字典内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.data_info
     *
     * @mbg.generated
     */
    private String dataInfo;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.sort
     *
     * @mbg.generated
     */
    private String sort;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.remarks
     *
     * @mbg.generated
     */
    private String remarks;
    //子结构
    private List<SysDbInfo> treeNode;

    public List<SysDbInfo> getTreeNode() {
        return treeNode;
    }

    public void setTreeNode(List<SysDbInfo> treeNode) {
        this.treeNode = treeNode;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.id
     *
     * @return the value of sys_db_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.id
     *
     * @param id the value for sys_db_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.parent_id
     *
     * @return the value of sys_db_info.parent_id
     *
     * @mbg.generated
     */
    public String getParentNum() {
        return parentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.parent_id
     *
     * @param parentNum the value for sys_db_info.parent_id
     *
     * @mbg.generated
     */
    public void setParentNum(String parentNum) {
        this.parentNum = parentNum == null ? null : parentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.data_num
     *
     * @return the value of sys_db_info.data_num
     *
     * @mbg.generated
     */
    public String getDataNum() {
        return dataNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.data_num
     *
     * @param dataNum the value for sys_db_info.data_num
     *
     * @mbg.generated
     */
    public void setDataNum(String dataNum) {
        this.dataNum = dataNum == null ? null : dataNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.data_info
     *
     * @return the value of sys_db_info.data_info
     *
     * @mbg.generated
     */
    public String getDataInfo() {
        return dataInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.data_info
     *
     * @param dataInfo the value for sys_db_info.data_info
     *
     * @mbg.generated
     */
    public void setDataInfo(String dataInfo) {
        this.dataInfo = dataInfo == null ? null : dataInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.sort
     *
     * @return the value of sys_db_info.sort
     *
     * @mbg.generated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.sort
     *
     * @param sort the value for sys_db_info.sort
     *
     * @mbg.generated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.remarks
     *
     * @return the value of sys_db_info.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.remarks
     *
     * @param remarks the value for sys_db_info.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}
