package com.chick.web.dictionary.entity;

import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_db_info
 */
public class SysDbInfoVO {
    /**
     * Database Column Remarks:
     *   字典id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   父节点编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.parent_num
     *
     * @mbg.generated
     */
    private String parentNum;

    /**
     * Database Column Remarks:
     *   字典编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.data_num
     *
     * @mbg.generated
     */
    private String dataNum;

    /**
     * Database Column Remarks:
     *   字典内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.data_info
     *
     * @mbg.generated
     */
    private String dataInfo;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.sort
     *
     * @mbg.generated
     */
    private String sort;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * Database Column Remarks:
     *   是否逻辑删除 1是0否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_db_info.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    //子结构
    private List<SysDbInfoVO> treeNode;

    public List<SysDbInfoVO> getTreeNode() {
        return treeNode;
    }

    public void setTreeNode(List<SysDbInfoVO> treeNode) {
        this.treeNode = treeNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.id
     *
     * @return the value of sys_db_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.id
     *
     * @param id the value for sys_db_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.parent_id
     *
     * @return the value of sys_db_info.parent_id
     *
     * @mbg.generated
     */
    public String getParentNum() {
        return parentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.parent_id
     *
     * @param parentNum the value for sys_db_info.parent_id
     *
     * @mbg.generated
     */
    public void setParentNum(String parentNum) {
        this.parentNum = parentNum == null ? null : parentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.data_num
     *
     * @return the value of sys_db_info.data_num
     *
     * @mbg.generated
     */
    public String getDataNum() {
        return dataNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.data_num
     *
     * @param dataNum the value for sys_db_info.data_num
     *
     * @mbg.generated
     */
    public void setDataNum(String dataNum) {
        this.dataNum = dataNum == null ? null : dataNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.data_info
     *
     * @return the value of sys_db_info.data_info
     *
     * @mbg.generated
     */
    public String getDataInfo() {
        return dataInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.data_info
     *
     * @param dataInfo the value for sys_db_info.data_info
     *
     * @mbg.generated
     */
    public void setDataInfo(String dataInfo) {
        this.dataInfo = dataInfo == null ? null : dataInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.sort
     *
     * @return the value of sys_db_info.sort
     *
     * @mbg.generated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.sort
     *
     * @param sort the value for sys_db_info.sort
     *
     * @mbg.generated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.remarks
     *
     * @return the value of sys_db_info.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.remarks
     *
     * @param remarks the value for sys_db_info.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.del_flag
     *
     * @return the value of sys_db_info.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.del_flag
     *
     * @param delFlag the value for sys_db_info.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.create_by
     *
     * @return the value of sys_db_info.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.create_by
     *
     * @param createBy the value for sys_db_info.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.create_date
     *
     * @return the value of sys_db_info.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.create_date
     *
     * @param createDate the value for sys_db_info.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.update_by
     *
     * @return the value of sys_db_info.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.update_by
     *
     * @param updateBy the value for sys_db_info.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_db_info.update_date
     *
     * @return the value of sys_db_info.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_db_info.update_date
     *
     * @param updateDate the value for sys_db_info.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}